# Site settings
title:          "&#60;&#47;&#62; shoveling"
description:    "생각대로 살지 않으면 사는대로 생각한다"
# baseurl:        "/"
url:            "https://blackwaterbread.github.io"

# Google Analytics
# google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         dayrain
  url:          https://github.com/blackwaterbread
  email:        blackwaterbrea@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale